// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_users_deleted_at,priority:1" json:"deleted_at"`
	Username    string         `gorm:"column:username;type:character varying(50);not null;uniqueIndex:idx_users_username,priority:1" json:"username"`
	Password    string         `gorm:"column:password;type:character varying(255);not null" json:"password"`
	Email       *string        `gorm:"column:email;type:character varying(100);index:idx_users_email,priority:1" json:"email"`
	Role        string         `gorm:"column:role;type:character varying(20);not null;index:idx_users_role,priority:1;default:user;comment:角色: user(普通用户), admin(管理员), super_admin(超级管理员)" json:"role"` // 角色: user(普通用户), admin(管理员), super_admin(超级管理员)
	IsAdmin     bool           `gorm:"column:is_admin;type:boolean;not null" json:"is_admin"`
	Status      string         `gorm:"column:status;type:character varying(20);not null;index:idx_users_status,priority:1;default:active;comment:状态: active(激活), inactive(未激活), banned(禁用)" json:"status"` // 状态: active(激活), inactive(未激活), banned(禁用)
	LastLoginAt *time.Time     `gorm:"column:last_login_at;type:timestamp with time zone;comment:最后登录时间" json:"last_login_at"`                                                                             // 最后登录时间
	LastLoginIP *string        `gorm:"column:last_login_ip;type:character varying(50);comment:最后登录IP" json:"last_login_ip"`                                                                                // 最后登录IP
	LoginCount  *int32         `gorm:"column:login_count;type:integer;comment:登录次数" json:"login_count"`                                                                                                    // 登录次数
	Provider    *string        `gorm:"column:provider;type:character varying(255);uniqueIndex:idx_provider,priority:1;comment:第三方登录" json:"provider"`                                                      // 第三方登录
	ProviderID  *string        `gorm:"column:provider_id;type:character varying(64);uniqueIndex:idx_provider,priority:2;comment:第三方登录id" json:"provider_id"`                                               // 第三方登录id
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
