// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserProfile = "user_profiles"

// UserProfile mapped from table <user_profiles>
type UserProfile struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64          `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_user_profiles_deleted_at,priority:1" json:"deleted_at"`
	Nickname  *string        `gorm:"column:nickname;type:character varying(50)" json:"nickname"`
	AvatarURL *string        `gorm:"column:avatar_url;type:character varying(500)" json:"avatar_url"`
	Bio       *string        `gorm:"column:bio;type:character varying(500)" json:"bio"`
	Gender    *int16         `gorm:"column:gender;type:smallint" json:"gender"`
	Birthday  *time.Time     `gorm:"column:birthday;type:date" json:"birthday"`
	Phone     *string        `gorm:"column:phone;type:character varying(20)" json:"phone"`
	Country   *string        `gorm:"column:country;type:character varying(50)" json:"country"`
	City      *string        `gorm:"column:city;type:character varying(50)" json:"city"`
	Address   *string        `gorm:"column:address;type:character varying(200)" json:"address"`
	Website   *string        `gorm:"column:website;type:character varying(200)" json:"website"`
	Github    *string        `gorm:"column:github;type:character varying(100)" json:"github"`
	Twitter   *string        `gorm:"column:twitter;type:character varying(100)" json:"twitter"`
}

// TableName UserProfile's table name
func (*UserProfile) TableName() string {
	return TableNameUserProfile
}
